# TENSORFLOW

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [3]:
fashion_mnist = keras.datasets.fashion_mnist

# separando treino e teste das imagens e rotulos
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4422102/4422102 [==============================] - 0s 0us/step


**conferindo treino**

In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
len(train_labels)

60000

In [6]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

**conferindo teste**

In [7]:
test_images.shape

(10000, 28, 28)

In [8]:
len(test_labels)

10000

In [9]:
np.unique(test_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [10]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [11]:
# forçando os valores a estarem entre 0 e 1
train_images = train_images/256.0
test_images = test_images/256.0

In [12]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)), #transformando a matriz em um vetor
    keras.layers.Dense(128, activation=tf.nn.relu), # pra ligar o neuronio da camada anterior no da proxima
    # relu: negativo se torna 0, positivo se mantem
    keras.layers.Dense(10, activation=tf.nn.softmax)
    # softmax: define bem as classes
])
model.summary() # quantos pesos ha e a estrutura da rede

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(optimizer='adam', # construção dos pesos
              loss='sparse_categorical_crossentropy', # metrica de erro, para trablhar com valores proximos a 0 e 1
              metrics=['accuracy']) # porcentagem de elementos classificados corretamente

In [16]:
model.fit(train_images, train_labels, epochs=5) # 5 interações no treinamento

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3254 - accuracy: 0.8822
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3065 - accuracy: 0.8881
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2889 - accuracy: 0.8928
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2762 - accuracy: 0.8980
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2646 - accuracy: 0.9018


In [17]:
# avaliar as imagens e rotulos e guardar as perdas e a acuracia
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

313/313 [==============================] - 1s 1ms/step - loss: 0.3785 - accuracy: 0.8736
Test accuracy: 0.8736000061035156


**avaliando individualmente**

In [18]:
predctions = model.predict(test_images)

313/313 [==============================] - 0s 1ms/step


In [19]:
predctions[0]

array([6.9529915e-06, 3.1902800e-06, 1.7991131e-06, 1.6175163e-07,
       2.7661310e-08, 7.5325064e-02, 8.3043033e-06, 1.5743782e-01,
       4.3415019e-07, 7.6721621e-01], dtype=float32)

a predição é dada pelo maior valor do array

In [20]:
np.argmax(predctions[0])

9

In [21]:
img = test_images[0]
print(img.shape)

(28, 28)


In [22]:
# expandindo as dimensoes da imagem, colocando ela em um vetor
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [23]:
predictions_single = model.predict(img)

print(predictions_single)

1/1 [==============================] - 0s 16ms/step
[[6.9529870e-06 3.1902721e-06 1.7991086e-06 1.6175122e-07 2.7661264e-08
  7.5325049e-02 8.3043051e-06 1.5743762e-01 4.3414991e-07 7.6721644e-01]]


In [24]:
np.argmax(predictions_single[0])

9